NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 30
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 18
NDefines.NGame.GAME_SPEED_SECONDS = { 1.0, 0.25, 0.1, 0.05, 0.0 }
NDefines.NCountry.EVENT_PROCESS_OFFSET = 30
NDefines_Graphics.NGraphics.MAPICON_GROUP_PASSES = 10
